Repository ai-dynamo/nixl, pull requests merged in 2025-08, with the labels that each got.

#647 Plugins should set rpath so that they can load their dependencies (#612)
  src/plugins/cuda_gds/meson.build
  src/plugins/gds_mt/meson.build
  src/plugins/gpunetio/meson.build
  src/plugins/hf3fs/meson.build
  src/plugins/mooncake/meson.build
  src/plugins/obj/meson.build
  src/plugins/posix/meson.build
  src/plugins/ucx/meson.build
  src/plugins/ucx_mo/meson.build
Labels: external-contribution, size/S

#650 NIXLBENCH: Install arch specific AWS CLI
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#568 .CI/SCRIPTS: Avoid tcp port collisions in tests
  .ci/scripts/common.sh
  .gitlab/test_cpp.sh
  .gitlab/test_plugins.sh
  .gitlab/test_python.sh
  test/gtest/common.cpp
  test/gtest/common.h
  test/gtest/main.cpp
  test/gtest/metadata_exchange.cpp
  test/gtest/plugins/meson.build
  test/gtest/test_transfer.cpp
Labels: size/L, Improvement, Test

#655 NIXLBENCH: Install arch specific AWS CLI - 0.5.0
  benchmark/nixlbench/contrib/Dockerfile
Labels: size/XS

#620 RUST: Implement queryMem binding
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
  src/bindings/rust/src/agent.rs
  src/bindings/rust/src/descriptors.rs
  src/bindings/rust/src/descriptors/query.rs
  src/bindings/rust/src/descriptors/reg.rs
  src/bindings/rust/src/lib.rs
  src/bindings/rust/stubs.cpp
  src/bindings/rust/tests/tests.rs
  src/bindings/rust/wrapper.cpp
  src/bindings/rust/wrapper.h
Labels: external-contribution, size/XL

#652 NIXL/GTEST: remove dead code
  test/gtest/test_transfer.cpp
Labels: external-contribution, size/S

#668 Use shallow clones in scripts if possible
  .gitlab/build.sh
  benchmark/nixlbench/contrib/Dockerfile
  contrib/Dockerfile
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/S

#671 NIXLBENCH: Add support for GDS_MT backend
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/M

#681 Bugfix: Replace select() with poll() in connectToIP to prevent stack smashing
  src/core/nixl_listener.cpp
Labels: external-contribution, size/M

#680 Added white background to figures of SB API doc
  docs/figures/nixl_high_level.png
  docs/figures/nixl_sb_api.png
Labels: external-contribution, size/XS

#591 Nixlbench: measure and display tail latency
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/nixl/nixl_worker.h
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.h
  benchmark/nixlbench/src/worker/worker.h
Labels: external-contribution, size/L

#627 [CI] Add new CI test to detect large PRs
  .github/workflows/pr-size-check.yml
Labels: size/M

#689 plugins/posix: Fix queue type message
  src/plugins/posix/posix_backend.cpp
Labels: external-contribution, size/S

#692 query_mem example fix
  examples/python/query_mem_example.py
Labels: external-contribution, size/XS

#685 BACKEND/UCX: cleanup AM based control path
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
Labels: external-contribution, size/L

#698 CI: Add iproute2 dependency
  .gitlab/build.sh
Labels: external-contribution, size/XS

#697 chore: Update release version for NIXL
  .ci/jenkins/pipeline/proj-jjb.yaml
  Cargo.lock
  Cargo.toml
  benchmark/nixlbench/meson.build
  examples/rust/Cargo.lock
  meson.build
  pyproject.toml
Labels: size/S

#709 OBJ: Remove backend options from default params map (#703)
  src/plugins/obj/obj_plugin.cpp
Labels: external-contribution, size/S

#718 Remove has_overlaps method from descList as it is not used.
  src/api/cpp/nixl_descriptors.h
  src/bindings/rust/src/descriptors/reg.rs
  src/bindings/rust/src/descriptors/xfer.rs
  src/bindings/rust/src/lib.rs
  src/bindings/rust/stubs.cpp
  src/bindings/rust/tests/tests.rs
  src/bindings/rust/wrapper.cpp
  src/bindings/rust/wrapper.h
  src/infra/nixl_descriptors.cpp
  test/nixl/desc_example.cpp
Labels: external-contribution, size/L

#717 Use standard signal name in python test script
  .gitlab/test_python.sh
Labels: external-contribution, size/XS

#690 BACKEND/UCX: fix req initialization in checkXfer
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/ucx/ucx_utils.cpp
  test/gtest/error_handling.cpp
Labels: external-contribution, size/L

#723 [GDS] bugfix - initialize CUfileDescr_t (#721)
  src/plugins/cuda_gds/gds_utils.cpp
Labels: external-contribution, size/XS

#726 NIXLBench: Check individual thread buffer size
  benchmark/kvbench/pyproject.toml
  benchmark/nixlbench/README.md
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/L

#727 NIXLBench: Check individual thread buffer size (#726)
  benchmark/kvbench/pyproject.toml
  benchmark/nixlbench/README.md
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/L

#708 [nixlbench]pass num_workers to ucx
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  src/plugins/ucx/ucx_backend.cpp
Labels: external-contribution, size/XS

#734 clang format the nixl_descriptors header
  src/api/cpp/nixl_descriptors.h
Labels: external-contribution, size/XL

#737 Added pythonic objects for xfer and dlist handles
  src/api/python/_api.py
Labels: external-contribution, size/L

#745 Do not bundle libcuda* and libcufile into the wheel
  contrib/build-wheel.sh
Labels: external-contribution, size/XS

#743 Fallback to manual CUDA detection when meson detection fails
  meson.build
Labels: external-contribution, size/S

#695 [HF3FS] add mempool
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  src/plugins/hf3fs/hf3fs_backend.cpp
  src/plugins/hf3fs/hf3fs_backend.h
  test/unit/plugins/hf3fs/nixl_hf3fs_mt_test.cpp
Labels: external-contribution, size/L

#705 Create host-side GPU transfer request API
  src/api/cpp/backend/backend_engine.h
  src/api/cpp/nixl.h
  src/core/agent_data.h
  src/core/nixl_agent.cpp
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
Labels: external-contribution, size/M

#744 CI: Build container job fixup
  .ci/jenkins/lib/build-container-matrix.yaml
Labels: external-contribution, size/XS
