Repository ai-dynamo/nixl, pull requests merged in 2025-05, with the labels that each got.

#221 python: minor test improvement
  examples/python/blocking_send_recv_example.py
  src/api/python/_api.py
Labels: size/S

#234 POSIX: merge posix plugin to main with CI changes
  .gitlab/build.sh
  .gitlab/test_cpp.sh
  .gitlab/test_python.sh
  README.md
  contrib/Dockerfile
  src/core/nixl_plugin_manager.cpp
  src/plugins/meson.build
  src/plugins/posix/README.md
  src/plugins/posix/meson.build
  src/plugins/posix/posix_backend.cpp
  src/plugins/posix/posix_backend.h
  src/plugins/posix/posix_plugin.cpp
  src/utils/common/status.h
  test/nixl/meson.build
  test/nixl/test_plugin.cpp
  test/unit/plugins/meson.build
  test/unit/plugins/posix/meson.build
  test/unit/plugins/posix/nixl_posix_test.cpp
Labels: size/XXL

#238 meson: don't require liburing
  README.md
  src/plugins/meson.build
Labels: size/S

#243 CI: disable POSIX CI test
  .gitlab/test_cpp.sh
  contrib/Dockerfile
  src/plugins/posix/README.md
Labels: size/M

#240 README: Clarify hostname for etcd server
  README.md
Labels: size/XS

#223 refactor: Prefer "using" over "typedef" guideline implementation
  src/api/cpp/nixl_descriptors.h
  src/api/cpp/nixl_types.h
  src/core/agent_data.h
  src/infra/mem_section.h
  src/plugins/ucx/ucx_backend.h
  src/plugins/ucx_mo/ucx_mo_backend.cpp
  src/plugins/ucx_mo/ucx_mo_backend.h
  src/utils/common/nixl_time.h
  src/utils/ucx/ucx_utils.h
Labels: external-contribution, size/M

#230 NIXLBench: Add ctrl-c handling for etcd cleanup
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
  benchmark/nixlbench/src/worker/worker.cpp
  benchmark/nixlbench/src/worker/worker.h
Labels: external-contribution, size/L

#231 NIXLBench: Use directory listing and generation for barrier
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
Labels: external-contribution, size/L

#233 NIXLBench: Persist environment until all ranks complete
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/worker/worker.cpp
  benchmark/nixlbench/src/worker/worker.h
Labels: external-contribution, size/S

#211 AGENT: Use std::unique_ptr for agent data
  src/api/cpp/nixl.h
  src/core/agent_data.h
  src/core/nixl_agent.cpp
Labels: external-contribution, size/M

#200 Extend nixl_test with multi-threading
  test/nixl/nixl_test.cpp
Labels: external-contribution, size/L

#202 refactor: updates for kv block manager
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
  src/bindings/rust/build.rs
  src/bindings/rust/src/lib.rs
  src/bindings/rust/src/tests.rs
Labels: size/L

#235 POSIX: Add more logs
  .gitlab/test_cpp.sh
  src/plugins/posix/posix_backend.cpp
  src/plugins/posix/posix_backend.h
Labels: external-contribution, size/S

#236 UCX backend error handling
  src/api/cpp/nixl_types.h
  src/core/nixl_agent.cpp
  src/core/nixl_plugin_manager.cpp
  src/infra/meson.build
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/ucx/meson.build
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/gtest/meson.build
  test/gtest/ucx_tests.cpp
Labels: external-contribution, size/XL

#250 CI: Change default runner labels for NIXL validation workflow
  .github/workflows/build_validation.yml
Labels: external-contribution, size/XS

#252 UCX: Only send request notification when requests have completed
  src/plugins/ucx/ucx_backend.cpp
Labels: external-contribution, size/M

#255 chore: update CODEOWNERS file
  CODEOWNERS
Labels: size/XS

#258 NIXLBench: Bug fixes to properly create desclist and calculate stat + read support for nvshmem worker
  benchmark/nixlbench/meson.build
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
  benchmark/nixlbench/src/worker/worker.cpp
  benchmark/nixlbench/src/worker/worker.h
Labels: size/M

#261 python: use torch.set_default_device in blocking_send_recv_example.py
  examples/python/blocking_send_recv_example.py
Labels: external-contribution, size/S

#268 TEST: fix improper rebase in nixl_test
  test/nixl/nixl_test.cpp
Labels: external-contribution, size/XS

#256 UCX: Fix potential memory leak with genNotif()
  src/plugins/ucx/ucx_backend.cpp
  src/utils/serdes/serdes.cpp
Labels: external-contribution, size/M

#262 posix: Updated implementation to support both AIO and Uring
  .gitlab/build.sh
  .gitlab/test_cpp.sh
  contrib/Dockerfile
  src/core/meson.build
  src/core/nixl_plugin_manager.cpp
  src/plugins/meson.build
  src/plugins/posix/README.md
  src/plugins/posix/aio_queue.cpp
  src/plugins/posix/aio_queue.h
  src/plugins/posix/async_queue.h
  src/plugins/posix/meson.build
  src/plugins/posix/posix_backend.cpp
  src/plugins/posix/posix_backend.h
  src/plugins/posix/posix_plugin.cpp
  src/plugins/posix/queue_factory_impl.h
  src/plugins/posix/uring_queue.cpp
  src/plugins/posix/uring_queue.h
  test/unit/plugins/posix/nixl_posix_test.cpp
Labels: size/XXL

#254 pytest: add more fixtures and unit tests for API features
  .gitlab/test_python.sh
  src/api/python/_api.py
  test/python/test_nixl_api.py
Labels: external-contribution, size/L

#259 UCX: refactor: Apply smart pointer resource management
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/plugins/ucx_mo/ucx_mo_backend.cpp
  src/plugins/ucx_mo/ucx_mo_backend.h
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/unit/utils/ucx/ucx_am_test.cpp
  test/unit/utils/ucx/ucx_worker_test.cpp
Labels: external-contribution, size/L

#246 TEST: Add data transfer test in gtest
  test/gtest/common.h
  test/gtest/meson.build
  test/gtest/test_transfer.cpp
Labels: external-contribution, size/L

#269 build: Miscellanous fixes
  meson.build
  src/core/nixl_agent.cpp
Labels: size/XS

#265 Agent: small fixes to commWorker
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
Labels: external-contribution, size/L

#274 Python: dependency and GDS example clarification
  examples/python/nixl_gds_example.py
  pyproject.toml
Labels: external-contribution, size/XS

#272 Agent API: new param metadataLabel for allowing user to label md in ETCD mode
  examples/cpp/nixl_etcd_example.cpp
  src/api/cpp/nixl.h
  src/api/cpp/nixl_types.h
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
Labels: external-contribution, size/L

#282 README: link to plugin requirements
  README.md
Labels: external-contribution, size/S

#283 chore: bump nixl versions to 0.2.1
  meson.build
  pyproject.toml
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
Labels: size/XS

#278 Dockerfile for building EFA wheel
  contrib/Dockerfile
Labels: size/M

#276 UCX: Fix worker address query to enable cuda-ipc
  src/utils/ucx/ucx_utils.cpp
Labels: external-contribution, size/XS

#286 UCX: Fix worker address query to enable cuda-ipc (#276)
  src/utils/ucx/ucx_utils.cpp
Labels: size/XS

#285 Dockerfile for building EFA wheel
  contrib/Dockerfile
Labels: size/M

#288 fix: add crate metadata for publishing
  src/bindings/rust/Cargo.toml
  src/bindings/rust/README.md
Labels: size/M

#289 fix: add crate metadata for publishing (#288)
  src/bindings/rust/Cargo.toml
  src/bindings/rust/README.md
Labels: size/M

#212 CI: Add AWS EFA testing infrastructure
  .github/workflows/aws_efa_validation.yml
  .github/workflows/copyright-check.ps1
  .gitignore
  contrib/aws-efa/README.md
  contrib/aws-efa/aws_job_def.json
  contrib/aws-efa/aws_test.sh
  contrib/aws-efa/aws_vars.template
Labels: size/L

#292 BUILD/TEST: Fix compilation on RedHat8
  meson.build
  src/plugins/posix/meson.build
  src/utils/ucx/ucx_utils.cpp
  test/gtest/ucx_tests.cpp
  test/nixl/meson.build
Labels: external-contribution, size/XS

#302 feat: add ARM (aarch64) build support for nixl-sys
  src/bindings/rust/build.rs
Labels: size/S

#304 feat: add ARM (aarch64) build support for nixl-sys (#302)
  src/bindings/rust/build.rs
Labels: size/S

#305 Release 0.2.1 cherry-pick: Fix compilation on RedHat8 (#292)
  meson.build
  src/plugins/posix/meson.build
  src/utils/ucx/ucx_utils.cpp
  test/gtest/ucx_tests.cpp
  test/nixl/meson.build
Labels: size/XS

#275 Update CODEOWNERS
  CODEOWNERS
Labels: external-contribution, size/XS

#295 Mark subset of data path methods with 'const' modifier
  src/api/cpp/backend/backend_engine.h
  src/api/cpp/nixl.h
  src/core/nixl_agent.cpp
  src/plugins/cuda_gds/gds_backend.cpp
  src/plugins/cuda_gds/gds_backend.h
  src/plugins/mooncake/mooncake_backend.cpp
  src/plugins/mooncake/mooncake_backend.h
  src/plugins/posix/posix_backend.cpp
  src/plugins/posix/posix_backend.h
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/plugins/ucx_mo/ucx_mo_backend.cpp
  src/plugins/ucx_mo/ucx_mo_backend.h
  test/gtest/mocks/mock_dram_engine.cpp
  test/gtest/mocks/mock_dram_engine.h
Labels: external-contribution, size/L

#310 nixlbench: Add support for POSIX plugin
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/nixl/nixl_worker.h
  benchmark/nixlbench/src/worker/worker.cpp
  src/plugins/posix/aio_queue.cpp
Labels: size/L

#308 Refactor UCX plugin glue.
  src/plugins/ucx/ucx_plugin.cpp
Labels: external-contribution, size/M

#321 build: Remove packages
  .codespellrc
  requirements.txt
Labels: size/XS

#323 build: Remove packages (#321)
  .codespellrc
  requirements.txt
Labels: size/XS

#297 Refactor UCX progress thread to remove busy-polling
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/unit/plugins/mooncake/mooncake_backend_test.cpp
  test/unit/plugins/ucx/ucx_backend_test.cpp
  test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
  test/unit/utils/ucx/ucx_am_test.cpp
  test/unit/utils/ucx/ucx_worker_test.cpp
Labels: external-contribution, size/L

#326 plugins/posix: Fix build on RHEL8/Manylinux
  src/plugins/posix/meson.build
Labels: size/M

#324 UCX: fix multi GPU scenario (#222)
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  src/plugins/ucx/ucx_backend.cpp
Labels: size/XS

#306 Benchmark: make it possible to build container with UCX built from source
  benchmark/nixlbench/contrib/Dockerfile
  benchmark/nixlbench/contrib/build.sh
Labels: external-contribution, size/M

#340 fix: add python and rust attribution files
  .pre-commit-config.yaml
  ATTRIBUTIONS-Python.md
  ATTRIBUTIONS-Rust.md
  test/README.md
Labels: size/XXL

#341 Updated ATTRIBUTIONS-CPP.md for 0.2.1 release
  ATTRIBUTIONS-CPP.md
  ATTRIBUTIONS.md
Labels: size/XXL

#332 BACKEND/UCX_MO: add ucx_error_handling_mode parameter
  src/plugins/ucx/ucx_plugin.cpp
  src/plugins/ucx_mo/meson.build
  src/plugins/ucx_mo/ucx_mo_plugin.cpp
  src/utils/ucx/meson.build
  src/utils/ucx/ucx_utils.h
  test/gtest/error_handling.cpp
Labels: external-contribution, size/M

#294 UCX: handle ucp_worker_create failure
  src/plugins/ucx/ucx_plugin.cpp
  src/utils/ucx/ucx_utils.cpp
Labels: external-contribution, size/S

#287 Refactor: Some C++ best practices.
  src/api/cpp/backend/backend_engine.h
  src/plugins/ucx/ucx_backend.h
Labels: external-contribution, size/L

#336 UCX: Set a CUDA context when loading remote MD from listener thread
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/stream/metadata_stream.cpp
  test/gtest/meson.build
  test/gtest/test_transfer.cpp
Labels: external-contribution, size/L

#327 pre-commit: Ignore crate in codespell
  .codespellrc
Labels: size/XS

#315 Agent: Bug fix: apply timeout to socket connection and add gtests for md exchange
  src/core/nixl_listener.cpp
  test/gtest/meson.build
  test/gtest/metadata_exchange.cpp
Labels: bug, size/XL

#303 Agent: Improve MD fetch and invalidate flow in ETCD mode using watchers
  examples/cpp/nixl_etcd_example.cpp
  src/core/nixl_listener.cpp
Labels: size/L

#329 Posix: Updated Uring Queue implementation
  src/api/cpp/backend/backend_aux.h
  src/plugins/posix/aio_queue.cpp
  src/plugins/posix/aio_queue.h
  src/plugins/posix/meson.build
  src/plugins/posix/posix_backend.cpp
  src/plugins/posix/posix_backend.h
  src/plugins/posix/posix_queue.h
  src/plugins/posix/queue_factory_impl.h
  src/plugins/posix/uring_queue.cpp
  src/plugins/posix/uring_queue.h
  src/utils/common/status.h
  test/unit/plugins/posix/nixl_posix_test.cpp
Labels: external-contribution, size/XL

#352 Dockerfile: Add RDMA libraries for UCX build
  contrib/Dockerfile
Labels: size/XS

#347 Timeout from poll() in progress thread after pthrDelay
  src/api/cpp/nixl_params.h
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
Labels: external-contribution, size/M

#248 Cost estimation
  src/api/cpp/backend/backend_engine.h
  src/api/cpp/nixl.h
  src/api/cpp/nixl_types.h
  src/bindings/python/nixl_bindings.cpp
  src/bindings/rust/src/lib.rs
  src/bindings/rust/wrapper.cpp
  src/bindings/rust/wrapper.h
  src/core/nixl_agent.cpp
  src/plugins/ucx/meson.build
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
Labels: external-contribution, size/L

#344 clang: Add clang format file
  .clang-format
Labels: size/M

#349 UCX_MO: Send notification when workers have completed in postXfer
  src/plugins/ucx_mo/ucx_mo_backend.cpp
  test/gtest/test_transfer.cpp
Labels: external-contribution, size/M

#343 Agent API: update sendLocalPartialMD to require label in etcd mode and update python bindings with label
  examples/cpp/nixl_etcd_example.cpp
  examples/python/partial_md_example.py
  src/api/cpp/nixl.h
  src/api/python/_api.py
  src/bindings/python/nixl_bindings.cpp
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
Labels: size/L

#247 SRC/BINDINGS/RUST: added missing APIs, reordered APIs to match python + tests
  .codespellrc
  src/bindings/rust/.gitignore
  src/bindings/rust/build.rs
  src/bindings/rust/src/lib.rs
  src/bindings/rust/src/tests.rs
  src/bindings/rust/wrapper.cpp
  src/bindings/rust/wrapper.h
Labels: size/XXL

#364 chore: add attributions files for NIXL
  .pre-commit-config.yaml
  ATTRIBUTIONS-CPP.md
  ATTRIBUTIONS-Python.md
  ATTRIBUTIONS-Rust.md
  ATTRIBUTIONS.md
  test/README.md
Labels: size/XXL

#301 fix: remove nixlGdsIOBatch::destroyBatch to prevent double cuFileBatchIODestroy call
  src/plugins/cuda_gds/gds_backend.cpp
  src/plugins/cuda_gds/gds_utils.cpp
  src/plugins/cuda_gds/gds_utils.h
Labels: external-contribution, size/XS

#373 UCX_MO: Check memory registration success to avoid invalid memory access
  src/plugins/ucx_mo/ucx_mo_backend.cpp
Labels: external-contribution, size/XS

#362 INFRA: Sections serialization: Only count remotely supported backends
  src/infra/nixl_memory_section.cpp
  test/gtest/metadata_exchange.cpp
Labels: external-contribution, size/M

#370 nixlbench: automatically detect NIXL lib path based on host CPU
  benchmark/nixlbench/meson.build
Labels: external-contribution, size/XS

#365 chore: update versions to 0.3.0
  benchmark/nixlbench/meson.build
  meson.build
  pyproject.toml
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
Labels: size/XS

#374 pyproject: Fix dependencies
  pyproject.toml
Labels: size/XS

#375 pyproject: Fix dependencies (#374)
  pyproject.toml
Labels: size/XS

#377 Reordered rust API
  contrib/Dockerfile
  src/bindings/rust/src/lib.rs
Labels: size/XL

#382 CI: Blossom CI initial commit
  .github/workflows/blossom-ci.yaml
Labels: external-contribution, size/M

#346 CI: Increase timeout for AWS job status check
  contrib/aws-efa/aws_test.sh
Labels: external-contribution, size/S

#376 Fix missing common/status.h compile error in 3fs plugin - 0.3.0
  src/plugins/hf3fs/hf3fs_backend.cpp
  src/plugins/hf3fs/hf3fs_log.h
  src/plugins/hf3fs/hf3fs_utils.cpp
Labels: size/M

#379 Reordered rust API (#377)
  contrib/Dockerfile
  src/bindings/rust/src/lib.rs
Labels: size/XL

#391 fix: consistent naming for NIXL KV Bench - 0.3.0
  benchmark/kvbench/examples/model_llama_3_1_8b.yaml
  benchmark/kvbench/models/deepseek_r1.py
  benchmark/kvbench/models/llama3_1.py
  benchmark/kvbench/models/models.py
Labels: external-contribution, size/M

#394 NIXLBench: add support for specifying GDS batch and pool sizes
  benchmark/kvbench/README.md
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/S

#399 chore: update attribution files for 0.3.0
  ATTRIBUTIONS-CPP.md
  ATTRIBUTIONS-Python.md
  ATTRIBUTIONS-Rust.md
Labels: size/XXL

#401 SRC/BINDINGS/RUST: Revert has_overlaps to pub
  src/bindings/rust/src/lib.rs
Labels: external-contribution, size/XS
