Repository ai-dynamo/nixl, pull requests merged in 2025-06, with the labels that each got.

#408 Build and container fixes for aarch64
  benchmark/nixlbench/contrib/Dockerfile
  benchmark/nixlbench/contrib/build.sh
  contrib/Dockerfile
  contrib/build-container.sh
  meson_options.txt
  src/plugins/cuda_gds/meson.build
Labels: external-contribution, size/M

#407 nixlbench: Add deps for IB devices
  benchmark/nixlbench/contrib/Dockerfile
  contrib/Dockerfile
Labels: external-contribution, size/XS

#396 UCX: Refactor nixlUcxWorker (and some related code).
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/meson.build
  src/utils/ucx/meson.build
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/unit/utils/ucx/ucx_am_test.cpp
  test/unit/utils/ucx/ucx_worker_test.cpp
Labels: external-contribution, size/L

#416 Fix for UCX build with IB dependencies
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#271 feat: rust bindings improvements
  src/bindings/rust/src/agent.rs
  src/bindings/rust/src/descriptors.rs
  src/bindings/rust/src/descriptors/reg.rs
  src/bindings/rust/src/descriptors/xfer.rs
  src/bindings/rust/src/lib.rs
  src/bindings/rust/src/notify.rs
  src/bindings/rust/src/utils.rs
  src/bindings/rust/src/utils/params.rs
  src/bindings/rust/src/utils/string_list.rs
  src/bindings/rust/src/xfer.rs
  src/bindings/rust/stubs.cpp
  src/bindings/rust/tests/tests.rs
  src/bindings/rust/wrapper.cpp
  src/bindings/rust/wrapper.h
Labels: size/XXL

#413 PLUGINS/UCX: Minor code cleanup related to notification lists.
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
Labels: external-contribution, size/M

#415 UCX: Finer grained progress to improve performance
  src/plugins/ucx/ucx_backend.cpp
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
Labels: external-contribution, size/S

#412 API/CPP: Replaced classes with only public members with structures.
  src/api/cpp/backend/backend_aux.h
  src/api/cpp/nixl_types.h
Labels: external-contribution, size/L

#430 Python: bindings optimizations and support numpy arrays for xfer_dlist
  .gitlab/test_python.sh
  examples/python/nixl_api_example.py
  src/api/python/_api.py
  src/bindings/python/nixl_bindings.cpp
  test/python/prep_xfer_perf.py
Labels: external-contribution, size/L

#429 UCX: Fix UCP AM usage (do not duplicate id in the header)
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
Labels: external-contribution, size/M

#381 build: Create Dockerfile.manylinux
  contrib/Dockerfile.manylinux
  contrib/build-container.sh
Labels: size/L

#398 nixlbench: enable VMM CUDA memory allocation
  benchmark/kvbench/README.md
  benchmark/kvbench/commands/args.py
  benchmark/kvbench/commands/nixlbench.py
  benchmark/nixlbench/README.md
  benchmark/nixlbench/meson.build
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/L

#443 CODEOWNERS: added roiedanino as codeowner of Rust bindings
  CODEOWNERS
Labels: external-contribution, size/XS

#438 chore: update attributions post 0.3.0 release
  ATTRIBUTIONS-CPP.md
  ATTRIBUTIONS-Python.md
  ATTRIBUTIONS-Rust.md
  README.md
Labels: size/XXL

#448 fix: GDS deps and Dockerfile updates
  contrib/Dockerfile
  contrib/Dockerfile.manylinux
  test/unit/plugins/cuda_gds/meson.build
Labels: external-contribution, size/XS

#404 Introduce GDAKI with DOCA GPUNetIO + DOCA RDMA, stream mode
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  contrib/Dockerfile
  contrib/build-container.sh
  meson.build
  src/api/cpp/backend/backend_aux.h
  src/api/cpp/nixl_types.h
  src/core/nixl_agent.cpp
  src/core/nixl_plugin_manager.cpp
  src/plugins/gpunetio/README.md
  src/plugins/gpunetio/gpunetio_backend.cpp
  src/plugins/gpunetio/gpunetio_backend.h
  src/plugins/gpunetio/gpunetio_backend_aux.h
  src/plugins/gpunetio/gpunetio_kernels.cu
  src/plugins/gpunetio/gpunetio_plugin.cpp
  src/plugins/gpunetio/gpunetio_utils.cpp
  src/plugins/gpunetio/meson.build
  src/plugins/meson.build
  test/README.md
  test/nixl/meson.build
  test/nixl/test_plugin.cpp
  test/unit/plugins/gpunetio/README.md
  test/unit/plugins/gpunetio/meson.build
  test/unit/plugins/gpunetio/nixl_gpunetio_stream_test.cu
  test/unit/plugins/meson.build
Labels: size/XXL

#459 NIXL: set env vars for best EFA performance
  contrib/build-container.sh
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
Labels: external-contribution, size/M

#462 NIXL: set env vars for best EFA performance (#459)
  contrib/build-container.sh
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
Labels: external-contribution, size/M

#464 Python: Fixed bad cast OBJ_SEG cast in nixl_bindings.cpp
  src/bindings/python/nixl_bindings.cpp
Labels: external-contribution, size/XS

#446 CI: Reduce log verbosity in AWS EFA test waiting loops
  contrib/aws-efa/aws_test.sh
Labels: external-contribution, size/S

#468 build: Add wheel-base to pass the the wheel building platform.
  contrib/build-container.sh
Labels: size/S

#469 build: Add wheel-base to pass the the wheel building platform. (#468)
  contrib/build-container.sh
Labels: size/S

#463 nixlbench: Add GPUNETIO debs to dockerfile
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/S

#466 contrib: Remove the lib.real from the LD_LIBRARY path
  benchmark/nixlbench/contrib/Dockerfile
  contrib/Dockerfile
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/S

#475 contrib: Clean up libcuda.so.1
  benchmark/nixlbench/contrib/Dockerfile
  contrib/Dockerfile
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/M

#474 clang: Add clang format file
  .clang-format
  .pre-commit-config.yaml
Labels: external-contribution, size/M

#472 nixlbench: Add GPUNETIO debs to dockerfile - 0.3.1
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/S

#485 SRC/BINDINGS/PYTHON: Fix handling of unsorted desc list passed with sorted=True
  src/bindings/python/nixl_bindings.cpp
  src/infra/nixl_descriptors.cpp
Labels: external-contribution, size/S, Python Bindings

#488 Upgrade ssl dependency for wheel
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/M

#489 Add missing UCX plugins to python wheel (#483)
  contrib/Dockerfile.manylinux
  contrib/wheel_add_ucx_plugins.py
Labels: external-contribution, size/L

#490 SRC/BINDINGS/PYTHON: Fix handling of unsorted desc list passed with s…
  src/bindings/python/nixl_bindings.cpp
  src/infra/nixl_descriptors.cpp
Labels: external-contribution, size/S

#491 Upgrade ssl dependency for wheel (#488)
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/M

#497 Compress wheel
  contrib/wheel_add_ucx_plugins.py
Labels: external-contribution, size/XS

#498 Compress wheel (#497)
  contrib/wheel_add_ucx_plugins.py
Labels: external-contribution, size/XS

#495 TEST/GTEST: Added mutex before logging.
  test/gtest/test_transfer.cpp
Labels: external-contribution, size/S

#487 NIXL/UCX: Added support for self notification
  src/core/nixl_agent.cpp
  src/plugins/ucx/ucx_backend.cpp
  test/gtest/test_transfer.cpp
Labels: external-contribution, size/M

#502 EXAMPLES/CPP: Fixed includes.
  examples/cpp/nixl_example.cpp
Labels: external-contribution, size/XS

#465 UCX: Check if UCX recognizes GPU mem correctly
  src/plugins/ucx/ucx_backend.cpp
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/unit/utils/ucx/ucx_worker_test.cpp
Labels: external-contribution, size/M

#467 AWS: Remove job retries and add GH metadata tags
  contrib/aws-efa/aws_test.sh
Labels: external-contribution, size/S

#479 Object storage plugin
  .gitignore
  contrib/Dockerfile
  src/core/meson.build
  src/core/nixl_plugin_manager.cpp
  src/plugins/meson.build
  src/plugins/obj/README.md
  src/plugins/obj/meson.build
  src/plugins/obj/obj_backend.cpp
  src/plugins/obj/obj_backend.h
  src/plugins/obj/obj_executor.h
  src/plugins/obj/obj_plugin.cpp
  src/plugins/obj/obj_s3_client.cpp
  src/plugins/obj/obj_s3_client.h
  subprojects/asio.wrap
  test/gtest/meson.build
  test/gtest/unit/main.cpp
  test/gtest/unit/meson.build
  test/gtest/unit/obj/meson.build
  test/gtest/unit/obj/obj.cpp
  test/nixl/test_plugin.cpp
Labels: external-contribution, size/XXL
