Repository ai-dynamo/nixl, pull requests merged in 2025-10, with the labels that each got.

#839 Fix libfabric double-release and resource cleanup issues
  src/utils/libfabric/libfabric_common.h
  src/utils/libfabric/libfabric_rail.cpp
  src/utils/libfabric/libfabric_rail_manager.cpp
Labels: external-contribution, size/M

#848 Activate venv in nixlbench container (#845)
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#847 Remove EFA installer dependency from build process
  .ci/assets/nixl-version-info.template
  .ci/jenkins/lib/test-matrix.yaml
  .gitlab/build.sh
Labels: external-contribution, size/S

#856 Progress the completion queue manually in case of Resource Unavailable
  src/utils/libfabric/libfabric_rail.cpp
  src/utils/libfabric/libfabric_rail.h
Labels: external-contribution, size/M

#842 CI: improve blossom job user experience
  .ci/jenkins/pipeline/proj-jjb.yaml
Labels: external-contribution, size/S

#850 Fix libfabric double-release and resource cleanup issues (#839)
  src/utils/libfabric/libfabric_common.h
  src/utils/libfabric/libfabric_rail.cpp
  src/utils/libfabric/libfabric_rail_manager.cpp
Labels: external-contribution, size/M

#859 [Libfabric]: retry operations
  src/utils/libfabric/libfabric_common.h
  src/utils/libfabric/libfabric_rail.cpp
Labels: external-contribution, size/L

#868 fix(libfabric): prevent double-free segfault in hwloc topology initialization
  src/utils/libfabric/libfabric_topology.cpp
Labels: external-contribution, size/M

#815 DEVICE/API: Change addresses to offsets and add channel_id
  src/api/cpp/nixl.h
  src/api/gpu/ucx/nixl_device.cuh
  src/core/nixl_agent.cpp
  src/plugins/ucx/ucx_backend.cpp
  src/utils/ucx/gpu_xfer_req_h.cpp
  src/utils/ucx/gpu_xfer_req_h.h
  src/utils/ucx/ucx_utils.h
  test/gtest/device_api/single_write_test.cu
  test/gtest/device_api_test.cu
Labels: external-contribution, size/L

#862 nixlbench: Make etcd optional for storage backends
  benchmark/nixlbench/README.md
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/worker.cpp
Labels: external-contribution, size/L

#822 [Test/Example] Added backend selection option for libfabric unit tests
  .ci/scripts/common.sh
  .gitlab/test_cpp.sh
  .gitlab/test_python.sh
  contrib/aws-efa/aws_vars.template
  examples/cpp/nixl_example.cpp
  test/nixl/agent_example.cpp
  test/python/conftest.py
  test/python/test_nixl_api.py
Labels: external-contribution, size/L
