Repository ai-dynamo/nixl, pull requests merged in 2025-09, with the labels that each got.

#722 Fix Error in barrier when testing block size above 1M
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
Labels: external-contribution, size/M

#748 CI: avoid /build comment to trigger blossom-ci
  .github/workflows/blossom-ci.yml
Labels: external-contribution, size/XS

#729 Improve populate method performance for not fully sorted inputs.
  src/infra/nixl_memory_section.cpp
  test/nixl/agent_example.cpp
Labels: external-contribution, size/L

#753 Upgrade DOCA to 3.1 in Dockerfiles
  contrib/Dockerfile
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/M

#754 benchmark/kvbench: Update to make consistent with nixlbench
  benchmark/kvbench/README.md
  benchmark/kvbench/commands/args.py
  benchmark/kvbench/commands/nixlbench.py
  benchmark/kvbench/main.py
Labels: external-contribution, size/L

#702 Agent: Add getXferTelemetry API.
  .gitlab/test_cpp.sh
  .gitlab/test_python.sh
  docs/telemetry.md
  src/api/cpp/nixl.h
  src/api/cpp/nixl_types.h
  src/api/python/_api.py
  src/bindings/python/nixl_bindings.cpp
  src/core/agent_data.h
  src/core/nixl_agent.cpp
  src/core/telemetry.cpp
  src/core/telemetry.h
  src/core/telemetry_event.h
  src/core/transfer_request.h
  test/gtest/telemetry_test.cpp
  test/gtest/test_transfer.cpp
  test/python/test_nixl_api.py
  test/python/test_nixl_bindings.py
Labels: external-contribution, size/XL

#762 chore: Update release version for NIXL
  .ci/jenkins/pipeline/proj-jjb.yaml
  Cargo.lock
  Cargo.toml
  benchmark/nixlbench/meson.build
  examples/rust/Cargo.lock
  meson.build
  pyproject.toml
Labels: size/S

#758 Nixlbench: Install torch with CUDA support
  benchmark/kvbench/pyproject.toml
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#775 Revert "CI: fix for blossom-ci auto trigger without comment (#771)"
  .github/workflows/blossom-ci.yml
Labels: external-contribution, size/XS

#768 Codeowners: create entry for python
  CODEOWNERS
Labels: external-contribution, size/XS

#776 CODEWONERS: Fix syntax
  CODEOWNERS
Labels: external-contribution, size/XS

#761 Removed the macros in nixl_agent.
  src/core/nixl_agent.cpp
  src/utils/common/nixl_log.h
  src/utils/serdes/meson.build
  src/utils/serdes/serdes.cpp
Labels: external-contribution, size/L

#769 Nixlbench: Install torch with CUDA support (#758)
  benchmark/kvbench/pyproject.toml
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#766 Make ETCD watch timeout configurable
  src/api/cpp/nixl_params.h
  src/core/nixl_listener.cpp
Labels: external-contribution, size/M

#783 CORE: Do not delete requests unless we own them (#782)
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  src/core/nixl_agent.cpp
  test/gtest/error_handling.cpp
Labels: external-contribution, size/S

#786 Fix signature mismatch in xferBenchNvshmemWorker::exchangeIOV
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.h
Labels: external-contribution, size/XS

#790 Simplify copyright-check
  .github/workflows/copyright-check.ps1
  .github/workflows/copyright-check.sh
  .github/workflows/copyright-checks.yml
  README.md
  test/gtest/device_api_test.cu
  test/python/desc_perf.py
Labels: size/XL

#798 DEVICE/API: Remove deviceMemList class and simplify create/release GPU request handle
  src/plugins/ucx/ucx_backend.cpp
  src/utils/ucx/gpu_xfer_req_h.cpp
  src/utils/ucx/gpu_xfer_req_h.h
  src/utils/ucx/meson.build
Labels: external-contribution, size/L

#801 Fix build when libfabric is not installed
  test/unit/utils/meson.build
Labels: external-contribution, size/XS

#805 DEVICE/API: Add nixlGpuWriteSignal API for local signal writing
  src/api/gpu/ucx/nixl_device.cuh
Labels: external-contribution, size/S

#809 Add same-agent transfer optimization with memcpy fallback
  src/plugins/libfabric/libfabric_backend.cpp
  src/utils/libfabric/libfabric_rail.cpp
Labels: external-contribution, size/M

#802 Replace full EFA installer with minimal EFA + custom libfabric build
  .gitlab/build.sh
  benchmark/nixlbench/contrib/Dockerfile
  contrib/Dockerfile
  contrib/Dockerfile.manylinux
  meson.build
Labels: external-contribution, size/L

#824 Add agent configuration support to Rust bindings
  src/bindings/rust/src/agent.rs
  src/bindings/rust/stubs.cpp
  src/bindings/rust/tests/tests.rs
  src/bindings/rust/wrapper.cpp
  src/bindings/rust/wrapper.h
Labels: external-contribution, size/L

#837 chore: Update release version for NIXL
  .ci/jenkins/pipeline/proj-jjb.yaml
  Cargo.lock
  Cargo.toml
  benchmark/nixlbench/meson.build
  examples/rust/Cargo.lock
  meson.build
  pyproject.toml
Labels: size/S
