Repository ai-dynamo/nixl, pull requests merged in 2025-04, with the labels that each got.

#136 release: prep for v0.1.1
  meson.build
  pyproject.toml
Labels: documentation

#111 README: update with instructions for build & install in a conda env
  README.md
  contrib/README.md
Labels: documentation

#142 CI: Add Doxygen documentation build support
  .gitlab/build.sh
  Doxyfile
  README.md
  meson.build
  meson_options.txt
Labels: documentation, enhancement

#153 Improve prints for C/Python
  examples/python/nixl_api_example.py
  src/api/python/_api.py
  src/core/nixl_agent.cpp
  src/core/nixl_plugin_manager.cpp
Labels: documentation

#165 python API: small change to provide clarity to check_remote_xfer
  src/api/python/__init__.py
  src/api/python/_api.py
Labels: documentation, size/S

#145 cuda_gds: cuFileBatch pool and reposting postXfer/getXferStatus for NIXL + GDS plugin
  src/core/nixl_agent.cpp
  src/plugins/cuda_gds/README.md
  src/plugins/cuda_gds/gds_backend.cpp
  src/plugins/cuda_gds/gds_backend.h
  src/plugins/cuda_gds/gds_plugin.cpp
  src/plugins/cuda_gds/gds_utils.cpp
  src/plugins/cuda_gds/gds_utils.h
  test/unit/plugins/cuda_gds/nixl_gds_test.cpp
Labels: bug, size/XXL

#137 Abseil-CPP Integration
  .gitignore
  meson.build
  subprojects/abseil-cpp.wrap
Labels: enhancement, size/L

#171 Descriptors: changed devID from 32-bits to 64-bits
  src/api/cpp/nixl_descriptors.h
  src/bindings/python/nixl_bindings.cpp
  src/infra/nixl_descriptors.cpp
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/plugins/ucx_mo/ucx_mo_backend.cpp
  src/plugins/ucx_mo/ucx_mo_backend.h
  test/nixl/desc_example.cpp
Labels: size/L

#162 BUILD: Add explicit libdl and thread dependencies
  meson.build
  src/core/meson.build
  src/plugins/ucx/meson.build
  src/plugins/ucx_mo/meson.build
  src/utils/stream/meson.build
  test/unit/plugins/ucx/meson.build
Labels: external-contribution, size/S

#173 Descriptors: code reorg and clean up
  src/api/cpp/backend/backend_aux.h
  src/api/cpp/nixl.h
  src/api/cpp/nixl_descriptors.h
  src/infra/nixl_descriptors.cpp
  src/infra/nixl_memory_section.cpp
  test/nixl/desc_example.cpp
Labels: size/L

#150 testing: gtest initial infrastructure
  meson_options.txt
  test/gtest/main.cpp
  test/gtest/meson.build
  test/gtest/mocks/meson.build
  test/gtest/mocks/mock_basic_plugin.cpp
  test/gtest/mocks/mock_dram_engine.cpp
  test/gtest/mocks/mock_dram_engine.h
  test/gtest/mocks/mock_dram_plugin.cpp
  test/gtest/plugin_manager.cpp
  test/meson.build
Labels: enhancement, size/XL

#161 UCX: Fix memory leak in nixlUcxEngine
  src/plugins/ucx/ucx_backend.cpp
Labels: bug, external-contribution, size/XS

#167 API: add 3 new NB APIs for metadata transfer with socket implementation
  .gitlab/test_cpp.sh
  src/api/cpp/nixl.h
  src/api/cpp/nixl_params.h
  src/core/agent_data.h
  src/core/meson.build
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
  src/utils/common/str_tools.h
  src/utils/stream/metadata_stream.cpp
  src/utils/stream/metadata_stream.h
  test/nixl/nixl_test.cpp
Labels: enhancement, size/XL

#181 memSection: minor perf improvement and style fixes for populate method
  src/infra/nixl_memory_section.cpp
Labels: size/M

#185 CI: Add plugin test
  .gitlab/test_cpp.sh
Labels: size/XS

#184 CI: run gtests
  .gitlab/test_cpp.sh
  test/gtest/meson.build
  test/gtest/mocks/meson.build
  test/nixl/test_plugin.cpp
Labels: size/S

#172 backend:ucx: Implement handler reuse
  src/core/nixl_agent.cpp
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/plugins/ucx_mo/ucx_mo_backend.cpp
  src/plugins/ucx_mo/ucx_mo_backend.h
  test/unit/plugins/ucx/ucx_backend_test.cpp
  test/unit/plugins/ucx_mo/ucx_mo_backend_test.cpp
Labels: size/XL

#159 Agent API: New method to get partial MD and allow partial MD loads
  src/api/cpp/nixl.h
  src/api/cpp/nixl_types.h
  src/core/agent_data.h
  src/core/nixl_agent.cpp
  src/infra/mem_section.h
  src/infra/nixl_descriptors.cpp
  src/infra/nixl_memory_section.cpp
  test/nixl/agent_example.cpp
Labels: external-contribution, size/XL

#168 DOCA plugin: enable GPU device backend postXfer
  src/api/cpp/backend/backend_aux.h
  src/api/cpp/backend/backend_engine.h
  src/api/cpp/nixl.h
  src/api/cpp/nixl_types.h
  src/core/nixl_agent.cpp
  src/plugins/doca/doca_backend.cpp
  src/plugins/doca/doca_backend.h
  src/plugins/doca/kernel_write.cu
  src/plugins/doca/meson.build
  src/plugins/doca/public/backend_plugin_doca_common.h
  src/plugins/doca/public/backend_plugin_doca_device.cuh
  test/nixl/meson.build
  test/nixl/nixl_doca_device_test.cu
  test/nixl/nixl_doca_stream_test.cu
Labels: external-contribution, size/XL

#180 Debug infra: Add NIXL logging and assertion macros
  meson.build
  meson_options.txt
  src/plugins/cuda_gds/meson.build
  src/utils/common/meson.build
  src/utils/common/nixl_log.cpp
  src/utils/common/nixl_log.h
  src/utils/meson.build
Labels: external-contribution, size/L

#189 cuda_gds: Remove cached file handle during deregister
  src/plugins/cuda_gds/gds_backend.cpp
  test/unit/plugins/cuda_gds/nixl_gds_test.cpp
Labels: size/S

#190 rust bindings: consolidate register_memory API
  src/bindings/rust/src/lib.rs
  src/bindings/rust/src/tests.rs
Labels: size/M

#188 API: sendPartial and python API updates
  .gitlab/test_python.sh
  examples/python/partial_md_example.py
  src/api/cpp/nixl.h
  src/api/cpp/nixl_types.h
  src/api/python/_api.py
  src/bindings/python/nixl_bindings.cpp
  src/core/agent_data.h
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
  test/nixl/nixl_test.cpp
Labels: size/L

#151 Implement multi-threading support
  src/api/cpp/nixl_params.h
  src/api/cpp/nixl_types.h
  src/core/agent_data.h
  src/core/nixl_agent.cpp
  src/core/nixl_plugin_manager.cpp
  src/core/plugin_manager.h
  src/core/sync.h
  src/utils/common/util.h
  test/gtest/meson.build
  test/gtest/mocks/mock_dram_engine.cpp
  test/gtest/mocks/mock_dram_engine.h
  test/gtest/multi_threading.cpp
  test/gtest/plugin_manager.cpp
  test/nixl/test_plugin.cpp
Labels: enhancement, external-contribution, size/XL

#192 plugin_mgr: Use filesystem from C++17
  src/core/nixl_plugin_manager.cpp
Labels: size/S

#196 rust: add cargo lock file and ignore build dir
  .gitignore
  src/bindings/rust/Cargo.lock
Labels: size/XS

#197 Dockerfile: add rust build support
  contrib/Dockerfile
Labels: size/S

#194 NIXLBench: Initial squashed commit for NIXLBench
  benchmark/nixlbench/README.md
  benchmark/nixlbench/contrib/Dockerfile
  benchmark/nixlbench/contrib/build.sh
  benchmark/nixlbench/meson.build
  benchmark/nixlbench/meson_options.txt
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
  benchmark/nixlbench/src/runtime/etcd/meson.build
  benchmark/nixlbench/src/runtime/meson.build
  benchmark/nixlbench/src/runtime/runtime.cpp
  benchmark/nixlbench/src/runtime/runtime.h
  benchmark/nixlbench/src/utils/meson.build
  benchmark/nixlbench/src/utils/scope_guard.h
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/meson.build
  benchmark/nixlbench/src/worker/nixl/meson.build
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/nixl/nixl_worker.h
  benchmark/nixlbench/src/worker/nvshmem/meson.build
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.h
  benchmark/nixlbench/src/worker/worker.cpp
  benchmark/nixlbench/src/worker/worker.h
Labels: size/XXL

#195 Fix iteration over remoteSockets during invalidation
  src/core/nixl_listener.cpp
Labels: external-contribution, size/S

#198 Add NIXL logging to agent and plugin manager
  src/core/meson.build
  src/core/nixl_agent.cpp
  src/core/nixl_plugin_manager.cpp
  src/utils/common/meson.build
  src/utils/common/nixl_log.cpp
Labels: external-contribution, size/M

#206 Debug Infra: Fix NIXL log level
  meson.build
  meson_options.txt
  src/utils/common/nixl_log.cpp
Labels: external-contribution, size/S

#203 API: checkRemoteMD call
  .gitlab/test_python.sh
  examples/python/blocking_send_recv_example.py
  examples/python/partial_md_example.py
  src/api/cpp/nixl.h
  src/api/cpp/nixl_params.h
  src/api/python/_api.py
  src/bindings/python/nixl_bindings.cpp
  src/core/meson.build
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
Labels: size/L

#215 fix: set version to 0.2.0
  meson.build
  pyproject.toml
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
Labels: size/XS

#216 fix: set version to 0.2.0
  meson.build
  pyproject.toml
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
Labels: size/XS

#199 Add ETCD support for NIXL MD
  README.md
  contrib/Dockerfile
  examples/cpp/meson.build
  examples/cpp/nixl_etcd_example.cpp
  meson.build
  meson_options.txt
  src/api/cpp/nixl_params.h
  src/core/agent_data.h
  src/core/meson.build
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
Labels: size/XL

#217 DEBUG: update release branch with new logging/debuggin and bug fix to said logging
  meson.build
  meson_options.txt
  src/core/meson.build
  src/core/nixl_agent.cpp
  src/core/nixl_plugin_manager.cpp
  src/utils/common/meson.build
  src/utils/common/nixl_log.cpp
Labels: size/L

#218 API: add option to use ETCD for metadata exchange to release branch
  .gitlab/test_python.sh
  README.md
  contrib/Dockerfile
  examples/cpp/meson.build
  examples/cpp/nixl_etcd_example.cpp
  examples/python/blocking_send_recv_example.py
  examples/python/partial_md_example.py
  meson.build
  meson_options.txt
  src/api/cpp/nixl.h
  src/api/cpp/nixl_params.h
  src/api/python/_api.py
  src/bindings/python/nixl_bindings.cpp
  src/core/agent_data.h
  src/core/meson.build
  src/core/nixl_agent.cpp
  src/core/nixl_listener.cpp
Labels: size/XXL

#213 UTILS/BUILD: Logging infra cleanups
  meson.build
  src/utils/common/nixl_log.h
Labels: external-contribution, size/M

#214 CI: Show system info
  .gitlab/test_cpp.sh
Labels: external-contribution, size/XS

#224 BUILD: Add stdc++fs link flag to for std::filesystem
  src/core/meson.build
Labels: external-contribution, size/XS

#220 README: mention pypi
  README.md
Labels: documentation, size/S

#228 tstamler: fix cuda deps
  .gitlab/build.sh
  src/core/meson.build
  test/nixl/agent_example.cpp
  test/nixl/meson.build
Labels: size/S
