Repository ai-dynamo/nixl, pull requests merged in 2025-07, with the labels that each got.

#506 UTILS/UCX: Added ucx::Config class.
  src/utils/ucx/config.cpp
  src/utils/ucx/config.h
  src/utils/ucx/meson.build
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
Labels: external-contribution, size/L

#436 CI: Add Jenkins job for NIXLBench container builds
  .ci/assets/nixlbench-version-info.json.template
  .ci/jenkins/lib/nixlbench-container-build-matrix.yaml
  .ci/jenkins/pipeline/proj-jjb.yaml
Labels: external-contribution, size/L

#523 POSIX: Fixed bugs on re-posting requests and added related test case
  src/plugins/posix/aio_queue.cpp
  src/plugins/posix/aio_queue.h
  src/plugins/posix/posix_backend.cpp
  src/plugins/posix/posix_queue.h
  src/plugins/posix/uring_queue.cpp
  src/plugins/posix/uring_queue.h
  test/unit/plugins/posix/nixl_posix_test.cpp
Labels: external-contribution, size/XL

#521 cuda_gds: Reducing the number of default batches created to 16
  src/plugins/cuda_gds/gds_backend.cpp
Labels: size/XS

#455 add hf3fs support in nixlbench
  benchmark/nixlbench/src/main.cpp
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/worker.cpp
  src/plugins/hf3fs/hf3fs_backend.cpp
  src/plugins/hf3fs/hf3fs_backend.h
Labels: external-contribution, size/L

#525 Add support for building python wheel on ARM 64
  contrib/Dockerfile.manylinux
Labels: external-contribution, size/S

#527 chore: Update release version for 0.4.0
  .ci/jenkins/pipeline/proj-jjb.yaml
  benchmark/nixlbench/meson.build
  examples/rust/Cargo.lock
  meson.build
  pyproject.toml
  src/bindings/rust/Cargo.lock
  src/bindings/rust/Cargo.toml
Labels: size/S

#533 BENCH: Fix UCX install path in dockerfile
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#536 UCX: Do not fail registration in mem check
  src/utils/ucx/ucx_utils.cpp
Labels: external-contribution, size/XS

#539 BENCH: Fix UCX install path in dockerfile - 0.4.0
  benchmark/nixlbench/contrib/Dockerfile
Labels: external-contribution, size/XS

#547 POSIX: Fix repost test logic error
  test/unit/plugins/posix/nixl_posix_test.cpp
Labels: external-contribution, size/M

#554 build: Remove aspostorage dependency in kvbench - 0.4.0
  benchmark/kvbench/pyproject.toml
Labels: size/XS

#553 CI: Bump the clang ver in GHA
  .github/workflows/clang-format.yml
Labels: external-contribution, size/XS

#524 Extend code style with current practices
  docs/CodeStyle.md
Labels: documentation, external-contribution, size/M

#496 UTILS/UCX: Minor improvements in nixlUcxWorker.
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_backend.h
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/unit/utils/ucx/ucx_am_test.cpp
  test/unit/utils/ucx/ucx_worker_test.cpp
Labels: external-contribution, size/L

#542 NIXLBENCH: update nixlbench/kvbench docs
  benchmark/kvbench/README.md
  benchmark/kvbench/commands/args.py
  benchmark/kvbench/commands/nixlbench.py
  benchmark/kvbench/docs/tutorial-gds.md
  benchmark/kvbench/main.py
Labels: external-contribution, size/L

#555 Obj fixes
  CODEOWNERS
  src/plugins/obj/obj_backend.cpp
  src/plugins/obj/obj_backend.h
  src/plugins/obj/obj_executor.h
  src/plugins/obj/obj_plugin.cpp
  src/plugins/obj/obj_s3_client.cpp
  src/plugins/obj/obj_s3_client.h
  test/gtest/unit/obj/obj.cpp
Labels: external-contribution, size/XL

#499 BACKEND/UCX: enable error handling mode peer by default
  src/plugins/ucx/ucx_backend.cpp
  src/utils/ucx/ucx_utils.cpp
  src/utils/ucx/ucx_utils.h
  test/gtest/error_handling.cpp
Labels: external-contribution, size/M

#510 Improve contributing guidelines
  CODEOWNERS
  CONTRIBUTING.md
  docs/Contributing.md
Labels: documentation, external-contribution, size/L

#565 NIXLBench/worker/nixl: clang format
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/L

#537 UCX/BACKEND: refactor nixlUcxEngine::nixlUcxEngine
  src/plugins/ucx/ucx_backend.cpp
  src/plugins/ucx/ucx_plugin.cpp
  src/utils/ucx/ucx_utils.cpp
Labels: external-contribution, size/M

#575 clang-tidy: Add config to enforce naming style
  .clang-tidy
Labels: external-contribution, size/S

#589 Fix plugin path lookup
  src/core/nixl_plugin_manager.cpp
Labels: external-contribution, size/XS

#576 Add support for parallel nixlbench tests
  benchmark/kvbench/commands/args.py
  benchmark/kvbench/commands/nixlbench.py
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.cpp
  benchmark/nixlbench/src/runtime/etcd/etcd_rt.h
  benchmark/nixlbench/src/runtime/etcd/python_bindings.cpp
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/worker.cpp
Labels: external-contribution, size/L

#520 [nixlbench] make large_block_iter_factor a configable option
  benchmark/nixlbench/README.md
  benchmark/nixlbench/src/utils/utils.cpp
  benchmark/nixlbench/src/utils/utils.h
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
  benchmark/nixlbench/src/worker/nvshmem/nvshmem_worker.cpp
Labels: external-contribution, size/M

#586 ci: Add direct links to child jobs in dispatcher build description
  .ci/jenkins/pipeline/proj-jjb.yaml
Labels: external-contribution, size/S

#599 obj: Add request checksum config toggle
  src/plugins/obj/README.md
  src/plugins/obj/obj_s3_client.cpp
Labels: external-contribution, size/S

#558 CODEOWNERS: Set default code owners to maintainers team
  CODEOWNERS
Labels: external-contribution, size/XS

#601 plugins/ucx: Remove leftover cufile header
  src/plugins/meson.build
  src/plugins/ucx/ucx_backend.cpp
  test/unit/utils/ucx/ucx_worker_test.cpp
Labels: external-contribution, size/XS

#595 fix: don't assume on library path construction in meson build file
  benchmark/nixlbench/meson.build
Labels: external-contribution, size/XS

#600 Fix issue in registerMem for OBJ plugin
  src/plugins/obj/obj_backend.cpp
Labels: external-contribution, size/XS

#355 CI: gtest: add etcd gtests etcd CI support
  .gitlab/build.sh
  .gitlab/test_cpp.sh
  .gitlab/test_python.sh
  examples/python/partial_md_example.py
  test/gtest/metadata_exchange.cpp
Labels: external-contribution, size/L

#613 Fix Obj plugin and tests according to project code style
  src/plugins/obj/obj_backend.cpp
  src/plugins/obj/obj_backend.h
  src/plugins/obj/obj_executor.h
  src/plugins/obj/obj_s3_client.cpp
  src/plugins/obj/obj_s3_client.h
  test/gtest/unit/agent/agent.cpp
  test/gtest/unit/main.cpp
  test/gtest/unit/obj/obj.cpp
Labels: external-contribution, size/L

#532 Add xfer time telemetry.
  src/core/agent_data.h
  src/core/nixl_agent.cpp
  src/core/transfer_request.h
Labels: external-contribution, size/M

#559 testing: Add plugin gtests infrastructure
  .github/workflows/aws_s3_validation.yml
  .gitlab/build.sh
  .gitlab/test_plugins.sh
  meson.build
  test/gtest/meson.build
  test/gtest/plugins/memory_handler.h
  test/gtest/plugins/meson.build
  test/gtest/plugins/obj_plugin.cpp
  test/gtest/plugins/plugins_common.h
  test/gtest/plugins/transfer_handler.h
Labels: external-contribution, size/XL

#544 [HF3FS] use shared memory to avoid memcpy to improve performance
  benchmark/nixlbench/src/utils/utils.cpp
  src/plugins/hf3fs/README.md
  src/plugins/hf3fs/hf3fs_backend.cpp
  src/plugins/hf3fs/hf3fs_backend.h
  src/plugins/hf3fs/hf3fs_utils.cpp
  src/plugins/hf3fs/hf3fs_utils.h
  src/utils/common/meson.build
  src/utils/common/uuid_v4.cpp
  src/utils/common/uuid_v4.h
  test/unit/plugins/hf3fs/nixl_hf3fs_test.cpp
Labels: external-contribution, size/XL

#632 Revert "PYTHON-PROJECT-WIDE: replaced print() calls with proper loggi…
  .ci/scripts/check_prints.sh
  .github/workflows/python-checks.yml
  benchmark/kvbench/commands/nixlbench.py
  benchmark/kvbench/models/model_config.py
  benchmark/kvbench/runtime/etcd_rt.py
  benchmark/kvbench/test/custom_traffic_perftest.py
  benchmark/kvbench/test/inference_workload_matgen.py
  benchmark/kvbench/test/sequential_custom_traffic_perftest.py
  benchmark/kvbench/test/traffic_pattern.py
  benchmark/nixlbench/src/runtime/etcd/test_etcd_runtime.py
  contrib/wheel_add_ucx_plugins.py
  examples/python/blocking_send_recv_example.py
  examples/python/nixl_api_example.py
  examples/python/nixl_gds_example.py
  examples/python/partial_md_example.py
  examples/python/query_mem_example.py
  src/api/python/_api.py
  src/api/python/logging.py
  src/api/python/meson.build
  src/api/python/python_logging.ini
  test/python/desc_perf.py
  test/python/prep_xfer_perf.py
  test/python/test_nixl_bindings.py
Labels: external-contribution, size/XL

#618 CODEOWNERS: Update owners to help with availability
  CODEOWNERS
Labels: external-contribution, size/S

#612 Plugins should set rpath so that they can load their dependencies
  src/plugins/cuda_gds/meson.build
  src/plugins/gds_mt/meson.build
  src/plugins/gpunetio/meson.build
  src/plugins/hf3fs/meson.build
  src/plugins/mooncake/meson.build
  src/plugins/obj/meson.build
  src/plugins/posix/meson.build
  src/plugins/ucx/meson.build
  src/plugins/ucx_mo/meson.build
Labels: external-contribution, size/S

#640 EXAMPLES/PYTHON: partial md example - fix test logic and warnings
  examples/python/partial_md_example.py
Labels: external-contribution, size/S

#638 NIXLBENCH: Fix memory allocation for non OBJ/storage use case (#637) - 0.5.0
  benchmark/nixlbench/src/worker/nixl/nixl_worker.cpp
Labels: external-contribution, size/XS

#644 RUST: Fix cargo package
  contrib/Dockerfile
Labels: external-contribution, size/XS

#651 chore: Update ATTRIBUTIONS-CPP.md
  ATTRIBUTIONS-CPP.md
Labels: size/M
